ALTER TABLE "appointment_booking_requests" ADD COLUMN "review_aging_decision" text;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD COLUMN "review_aging_decided_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD COLUMN "review_aging_decided_by_user_id" text;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD COLUMN "review_aging_cue_status" text;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD COLUMN "review_aging_age_hours" integer;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD COLUMN "review_aging_decision" text;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD COLUMN "review_aging_decided_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD COLUMN "review_aging_decided_by_user_id" text;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD COLUMN "review_aging_cue_status" text;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD COLUMN "review_aging_age_hours" integer;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD CONSTRAINT "appointment_booking_requests_review_aging_decided_by_user_id_users_id_fk" FOREIGN KEY ("review_aging_decided_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD CONSTRAINT "calendar_scheduling_requests_review_aging_decided_by_user_id_users_id_fk" FOREIGN KEY ("review_aging_decided_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD CONSTRAINT "appointment_booking_requests_review_aging_decision_value" CHECK ("appointment_booking_requests"."review_aging_decision" is null or "appointment_booking_requests"."review_aging_decision" in ('acknowledged', 'follow_up_required', 'defer_review'));--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD CONSTRAINT "appointment_booking_requests_review_aging_cue_status_value" CHECK ("appointment_booking_requests"."review_aging_cue_status" is null or "appointment_booking_requests"."review_aging_cue_status" in ('aging', 'stale'));--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD CONSTRAINT "appointment_booking_requests_review_aging_age_nonnegative" CHECK ("appointment_booking_requests"."review_aging_age_hours" is null or "appointment_booking_requests"."review_aging_age_hours" >= 0);--> statement-breakpoint
ALTER TABLE "appointment_booking_requests" ADD CONSTRAINT "appointment_booking_requests_review_aging_decision_complete" CHECK (("appointment_booking_requests"."review_aging_decision" is null and "appointment_booking_requests"."review_aging_decided_at" is null and "appointment_booking_requests"."review_aging_decided_by_user_id" is null and "appointment_booking_requests"."review_aging_cue_status" is null and "appointment_booking_requests"."review_aging_age_hours" is null) or ("appointment_booking_requests"."review_aging_decision" is not null and "appointment_booking_requests"."review_aging_decided_at" is not null and "appointment_booking_requests"."review_aging_decided_by_user_id" is not null and "appointment_booking_requests"."review_aging_cue_status" is not null and "appointment_booking_requests"."review_aging_age_hours" is not null));--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD CONSTRAINT "calendar_scheduling_requests_review_aging_decision_value" CHECK ("calendar_scheduling_requests"."review_aging_decision" is null or "calendar_scheduling_requests"."review_aging_decision" in ('acknowledged', 'follow_up_required', 'defer_review'));--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD CONSTRAINT "calendar_scheduling_requests_review_aging_cue_status_value" CHECK ("calendar_scheduling_requests"."review_aging_cue_status" is null or "calendar_scheduling_requests"."review_aging_cue_status" in ('aging', 'stale'));--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD CONSTRAINT "calendar_scheduling_requests_review_aging_age_nonnegative" CHECK ("calendar_scheduling_requests"."review_aging_age_hours" is null or "calendar_scheduling_requests"."review_aging_age_hours" >= 0);--> statement-breakpoint
ALTER TABLE "calendar_scheduling_requests" ADD CONSTRAINT "calendar_scheduling_requests_review_aging_decision_complete" CHECK (("calendar_scheduling_requests"."review_aging_decision" is null and "calendar_scheduling_requests"."review_aging_decided_at" is null and "calendar_scheduling_requests"."review_aging_decided_by_user_id" is null and "calendar_scheduling_requests"."review_aging_cue_status" is null and "calendar_scheduling_requests"."review_aging_age_hours" is null) or ("calendar_scheduling_requests"."review_aging_decision" is not null and "calendar_scheduling_requests"."review_aging_decided_at" is not null and "calendar_scheduling_requests"."review_aging_decided_by_user_id" is not null and "calendar_scheduling_requests"."review_aging_cue_status" is not null and "calendar_scheduling_requests"."review_aging_age_hours" is not null));