import type { StaffReportingWorkspaceResponse } from "./types";

export function emptyStaffReportingWorkspace(): StaffReportingWorkspaceResponse {
  return {
    generatedAt: new Date(0).toISOString(),
    definitions: [],
    exportProfiles: [],
    exportProfileAlignment: {
      status: "read_only_metadata_alignment",
      staffReportProfiles: [],
      financialFieldProfiles: [],
      differences: [],
      sharedSafeguards: {
        customSql: false,
        biEmbeds: false,
        scheduledExecution: false,
        scheduledDelivery: false,
        rawBodyStorage: false,
        paymentProcessorExposure: false,
        paymentCreation: false,
        paymentAllocation: false,
        invoiceMutation: false,
        trustPosting: false,
        certificationClaims: false,
      },
    },
    expenseCategoryAccountingExportProfileSummary: {
      status: "read_only_metadata_preview",
      profileId: "op_expense_category_accounting_summary",
      label: "OP expense category accounting summary",
      source: "open_practice_authored_metadata",
      financialProfileReference: "billing_operational_records_json",
      categoryCounts: {
        total: 0,
        active: 0,
        inactive: 0,
        defaultReimbursable: 0,
        reimbursableAllowed: 0,
        firmDefault: 0,
        scoped: 0,
        mapped: 0,
        omitted: 0,
        mappingLimit: 8,
      },
      mappings: [],
      safeguards: {
        externalAccountingProvider: false,
        exportSerializationChange: false,
        invoiceRecalculation: false,
        paymentMutation: false,
        trustPosting: false,
        certifiedAccountingClaim: false,
      },
    },
    reports: [],
    history: [],
    scheduleReadinessSummary: {
      totalDefinitions: 0,
      manualExportReadyDefinitions: 0,
      manualOnlyDefinitionKeys: [],
      recentExportRequestCount: 0,
      scheduledDefinitionCount: 0,
      automaticExecution: false,
      scheduledEmailDeliveryEnabled: false,
      rawReportBodyStorage: false,
    },
    reportBuilderPosture: {
      status: "metadata_only",
      savedDefinitionsOnly: true,
      filterCount: 0,
      groupingCount: 0,
      exportProfileCount: 0,
      customSql: false,
      biEmbeds: false,
      broadReportExecution: false,
      mutableDefinitionBuilder: false,
      rawReportBodyStorage: false,
    },
    exportJobPosture: {
      queueName: "reports",
      jobName: "staff_report_export",
      historyCount: 0,
      boundedMetadataOnly: true,
      storesReportBodiesInJobMetadata: false,
      downloadsRegenerateProjection: true,
      scheduledDeliveryJobs: false,
    },
    workspacePolicy: {
      customSql: false,
      biEmbeds: false,
      scheduledEmailDelivery: false,
      rawReportBodiesInJobMetadata: false,
    },
  };
}
