import type { AuditEvent } from "./audit.js";

export type AuditEventCategory =
  | "access"
  | "audit_integrity"
  | "billing"
  | "calendar"
  | "communications"
  | "contacts"
  | "conflicts"
  | "documents"
  | "drafting"
  | "intake"
  | "legal_clinic"
  | "legal_research"
  | "matter_lifecycle"
  | "operations"
  | "outbound_webhooks"
  | "portal"
  | "setup"
  | "signatures"
  | "trust"
  | "unknown";

export type AuditMatterScopeHint = "firm" | "matter" | "optional_matter" | "derived";
export type AuditActorHint =
  | "authenticated_user"
  | "provider_callback"
  | "public_portal_actor"
  | "setup_owner"
  | "system_seed"
  | "unknown";

export interface AuditEventTaxonomyDefinition {
  action: string;
  category: AuditEventCategory;
  resourceType?: string;
  matterScope: AuditMatterScopeHint;
  actorHint: AuditActorHint;
  matterMetadataKeys: readonly string[];
  resourceMetadataKeys: readonly string[];
  actorMetadataKeys: readonly string[];
}

export interface AuditEventClassification {
  action: string;
  category: AuditEventCategory;
  known: boolean;
  expectedResourceType?: string;
  resourceType: string;
  matterScope: AuditMatterScopeHint;
  actorHint: AuditActorHint;
  metadataHints: {
    matter: readonly string[];
    resource: readonly string[];
    actor: readonly string[];
  };
  hasMatterId: boolean;
  resourceTypeMatches: boolean;
}

export interface AuditEventTaxonomySummary {
  total: number;
  known: number;
  unknown: number;
  byCategory: Partial<Record<AuditEventCategory, number>>;
  byMatterScope: Partial<Record<AuditMatterScopeHint, number>>;
  byActorHint: Partial<Record<AuditActorHint, number>>;
  matterScopedWithoutMatterId: number;
  resourceTypeMismatches: Array<{
    action: string;
    expectedResourceType: string;
    observedResourceType: string;
    count: number;
  }>;
  unknownActions: string[];
}

const RESOURCE_ID_KEYS = [
  "artifactId",
  "attendeeId",
  "credentialId",
  "documentId",
  "draftId",
  "emailId",
  "eventId",
  "externalId",
  "invoiceId",
  "jobId",
  "linkId",
  "packageId",
  "proposalId",
  "ratePresetId",
  "providerEventId",
  "providerRequestId",
  "retryOfJobId",
  "sessionId",
  "signatureRequestId",
  "templateId",
  "templateDraftId",
  "previewSnapshotId",
  "deliveryId",
  "billingPeriodLockId",
  "transactionId",
  "uploadId",
  "contactId",
  "relationshipId",
  "matterAssociationId",
  "portalGrantId",
] as const;

const MATTER_KEYS = ["matterId"] as const;
const ACTOR_KEYS = [
  "actorId",
  "actorType",
  "createdByUserId",
  "reviewedByUserId",
  "requestedByUserId",
] as const;
const WORKFLOW_RESOURCE_KEYS = [
  "requestId",
  "workflowStatus",
  "beforeStatus",
  "expectedStatus",
  "afterStatus",
  "attemptNumber",
  "maxAttempts",
  "retryOfJobId",
  "nextAttemptAt",
  "idempotencyKeyPresent",
  "errorSummary",
] as const;

function define(
  definition: Omit<
    AuditEventTaxonomyDefinition,
    "matterMetadataKeys" | "resourceMetadataKeys" | "actorMetadataKeys"
  > &
    Partial<
      Pick<
        AuditEventTaxonomyDefinition,
        "matterMetadataKeys" | "resourceMetadataKeys" | "actorMetadataKeys"
      >
    >,
): AuditEventTaxonomyDefinition {
  return {
    matterMetadataKeys: MATTER_KEYS,
    resourceMetadataKeys: RESOURCE_ID_KEYS,
    actorMetadataKeys: ACTOR_KEYS,
    ...definition,
  };
}

export const auditEventTaxonomyDefinitions = [
  define({
    action: "setup.completed",
    category: "setup",
    resourceType: "firm",
    matterScope: "firm",
    actorHint: "setup_owner",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["ownerUserId", "firstMatterId", "smtpConfigured", "imapConfigured"],
    actorMetadataKeys: ["ownerUserId"],
  }),
  define({
    action: "auth_credential.password_setup_token.created",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "expiresInHours"],
  }),
  define({
    action: "auth_credential.password.updated",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "unknown",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "method"],
  }),
  define({
    action: "auth_credential.recovery_codes.generated",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "codeCount"],
  }),
  define({
    action: "auth_credential.recovery_code.used",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "unknown",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "method"],
  }),
  define({
    action: "auth_credential.passkey.created",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "credentialId", "deviceType", "backedUp"],
  }),
  define({
    action: "auth_credential.passkey.deleted",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "credentialId"],
  }),
  define({
    action: "auth_credential.mfa.enabled",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId", "passkeyCount"],
  }),
  define({
    action: "auth_credential.mfa.disabled",
    category: "access",
    resourceType: "auth_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["userId"],
  }),
  define({
    action: "matter.opened",
    category: "matter_lifecycle",
    resourceType: "matter",
    matterScope: "matter",
    actorHint: "system_seed",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["jurisdiction", "practiceArea"],
    actorMetadataKeys: [],
  }),
  define({
    action: "matter.lifecycle_transition_reviewed",
    category: "matter_lifecycle",
    resourceType: "matter",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "transitionRecordId",
      "transition",
      "currentStatus",
      "targetStatus",
      "readiness",
      "blockerCount",
      "reasonPresent",
      "reviewOnly",
    ],
    actorMetadataKeys: ["reviewedByUserId"],
  }),
  define({
    action: "matter.lifecycle_command_executed",
    category: "matter_lifecycle",
    resourceType: "matter",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "transitionRecordId",
      "lifecycleCommand",
      "beforeStatus",
      "expectedStatus",
      "afterStatus",
      "matterStatusChanged",
      "closedOnChanged",
      "portalAccessChanged",
      "taskChanged",
      "assignmentChanged",
      "billingChanged",
      "trustChanged",
      "retentionChanged",
      "cleanupRun",
      "reasonPresent",
      "idempotencyKeyPresent",
      "reviewFirst",
    ],
    actorMetadataKeys: ["executedByUserId"],
  }),
  define({
    action: "conflict_check.completed",
    category: "conflicts",
    resourceType: "conflict_check",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["resultCount", "includeClosedMatters", "partyRole"],
  }),
  define({
    action: "contact.created",
    category: "contacts",
    resourceType: "contact",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "kind", "status", "aliasCount", "identifierTypes"],
  }),
  define({
    action: "contact.updated",
    category: "contacts",
    resourceType: "contact",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "changedFields", "status"],
  }),
  define({
    action: "contact.archived",
    category: "contacts",
    resourceType: "contact",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "changedFields", "status"],
  }),
  define({
    action: "contact_history_export.requested",
    category: "contacts",
    resourceType: "contact_history_export",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "contactId",
      "matterId",
      "matterScoped",
      "jobId",
      "purpose",
      "reviewReasonPresent",
      "generatedCategoryCount",
      "timelineEntryCount",
      "matterAssociationCount",
      "portalGrantCount",
      "conflictSummaryCount",
      "documentHoldCueCount",
      "retentionHoldCueCount",
      "downloadExpiresAt",
      "enqueueStatus",
      "idempotencyKeyPresent",
      "retentionPosture",
      "legalHoldPosture",
      "privacyPosture",
      "storedBody",
      "retainedExportArtifact",
      "deletionAutomation",
      "retentionDeadline",
      "legalHoldOverride",
    ],
  }),
  define({
    action: "contact_history_export.downloaded",
    category: "contacts",
    resourceType: "contact_history_export",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "contactId",
      "matterId",
      "matterScoped",
      "jobId",
      "purpose",
      "downloadExpiresAt",
      "retentionPosture",
      "legalHoldPosture",
      "privacyPosture",
      "storedBody",
      "retainedExportArtifact",
      "deletionAutomation",
      "retentionDeadline",
      "legalHoldOverride",
    ],
  }),
  define({
    action: "contact.relationship.created",
    category: "contacts",
    resourceType: "contact_relationship",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "relatedContactId", "relationshipKind", "status"],
  }),
  define({
    action: "contact.relationship.updated",
    category: "contacts",
    resourceType: "contact_relationship",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "relatedContactId", "relationshipKind", "status"],
  }),
  define({
    action: "contact.matter_association.created",
    category: "contacts",
    resourceType: "matter_party",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "matterAssociationId", "partyRole", "status"],
  }),
  define({
    action: "contact.matter_association.updated",
    category: "contacts",
    resourceType: "matter_party",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "matterAssociationId", "partyRole", "status"],
  }),
  define({
    action: "contact_quality_decision.recorded",
    category: "contacts",
    resourceType: "contact_quality_review_decision",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    matterMetadataKeys: ["matterId"],
    resourceMetadataKeys: [
      "contactId",
      "signalKind",
      "decision",
      "relatedContactCount",
      "sourceRecordId",
      "evidenceKeyCount",
    ],
  }),
  define({
    action: "portal.grant.created",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "system_seed",
    resourceMetadataKeys: ["permissions"],
    actorMetadataKeys: [],
  }),
  define({
    action: "portal.account_setup.created",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "accountUserId",
      "contactId",
      "grantStatus",
      "setupTokenStatus",
      "permissions",
      "expiresAt",
    ],
  }),
  define({
    action: "portal.grant.updated",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus", "permissions"],
  }),
  define({
    action: "portal.grant.invited",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus", "permissions", "expiresAt"],
  }),
  define({
    action: "portal.grant.activated",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus"],
  }),
  define({
    action: "portal.grant.suspended",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus"],
  }),
  define({
    action: "portal.grant.expired",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus"],
  }),
  define({
    action: "portal.grant.revoked",
    category: "portal",
    resourceType: "portal_grant",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["contactId", "portalGrantId", "grantStatus"],
  }),
  define({
    action: "share_link.created",
    category: "portal",
    resourceType: "share_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["documentIds", "expiresAt", "requiresEmailVerification"],
  }),
  define({
    action: "share_link.revoked",
    category: "portal",
    resourceType: "share_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["revokedAt"],
  }),
  define({
    action: "external_upload.created",
    category: "portal",
    resourceType: "external_upload",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["expiresAt", "requiresEmailVerification"],
  }),
  define({
    action: "external_upload.revoked",
    category: "portal",
    resourceType: "external_upload",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["revokedAt"],
  }),
  define({
    action: "external_upload.document_reviewed",
    category: "portal",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: WORKFLOW_RESOURCE_KEYS,
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "document.upload_intent.created",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["documentId", "provider", "storageDisabled"],
  }),
  define({
    action: "document.upload.completed",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["documentId", "provider", "bytes", "status"],
  }),
  define({
    action: "document.scan_status.updated",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["documentId", "scanStatus", "provider"],
  }),
  define({
    action: "document.retention_hold_review.recorded",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "documentId",
      "decision",
      "reason",
      "reviewAfterPresent",
      "minimumRetainThroughPresent",
      "retentionHoldCueCount",
      "retentionPosture",
      "destructiveAction",
      "retentionDeadlineEnforced",
      "legalHoldOverride",
      "retainedExportBody",
    ],
  }),
  define({
    action: "document_processing.ocr.queued",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: WORKFLOW_RESOURCE_KEYS,
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "document_processing.conversion_review.queued",
    category: "documents",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      ...WORKFLOW_RESOURCE_KEYS,
      "documentId",
      "extractionId",
      "sourceTextLength",
    ],
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "document_processing.ocr_provider.updated",
    category: "operations",
    resourceType: "provider_setting",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["providerKind", "providerKey", "enabled"],
  }),
  define({
    action: "intake_session.created",
    category: "intake",
    resourceType: "intake_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "intake_answer_snapshot.created",
    category: "intake",
    resourceType: "intake_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["intakeSessionId", "snapshotId", "questionCount"],
  }),
  define({
    action: "intake_generated_document.created",
    category: "intake",
    resourceType: "generated_document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["documentId", "intakeSessionId", "templateId"],
  }),
  define({
    action: "intake.package.assembly_requested",
    category: "intake",
    resourceType: "intake_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["packageId", "jobId", "documentCount"],
  }),
  define({
    action: "intake.package.generated",
    category: "intake",
    resourceType: "intake_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["packageId", "documentCount", "signatureRequestCount"],
  }),
  define({
    action: "intake_template.created",
    category: "intake",
    resourceType: "intake_template",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["templateId", "itemCount", "version"],
  }),
  define({
    action: "intake_template.updated",
    category: "intake",
    resourceType: "intake_template",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["templateId", "itemCount", "version"],
  }),
  define({
    action: "intake_form_link.created",
    category: "intake",
    resourceType: "intake_form_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["intakeSessionId", "expiresAt", "itemCount"],
  }),
  define({
    action: "intake_form_review.accepted",
    category: "intake",
    resourceType: "intake_form_review",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "intakeSessionId",
      "formLinkId",
      "answerSnapshotId",
      "decision",
      "taskId",
    ],
  }),
  define({
    action: "intake_form_review.rejected",
    category: "intake",
    resourceType: "intake_form_review",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "intakeSessionId",
      "formLinkId",
      "answerSnapshotId",
      "decision",
      "taskId",
    ],
  }),
  define({
    action: "intake_form_review.request_more_info",
    category: "intake",
    resourceType: "intake_form_review",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "intakeSessionId",
      "formLinkId",
      "answerSnapshotId",
      "decision",
      "followUpFormLinkId",
      "taskId",
    ],
  }),
  define({
    action: "intake_signature_request.created",
    category: "intake",
    resourceType: "signature_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["intakeSessionId", "signatureRequestId", "signerCount"],
  }),
  define({
    action: "signature_request.created",
    category: "signatures",
    resourceType: "signature_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["signatureRequestId", "provider", "signerCount", "documentCount"],
  }),
  define({
    action: "signature_provider_event.recorded",
    category: "signatures",
    resourceType: "signature_request",
    matterScope: "derived",
    actorHint: "provider_callback",
    resourceMetadataKeys: ["signatureRequestId", "provider", "providerEventId", "status"],
  }),
  define({
    action: "signature_embedded_event.recorded",
    category: "signatures",
    resourceType: "signature_request",
    matterScope: "derived",
    actorHint: "public_portal_actor",
    resourceMetadataKeys: ["signatureRequestId", "eventType", "signerId"],
  }),
  define({
    action: "draft.created",
    category: "drafting",
    resourceType: "draft",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId", "version"],
  }),
  define({
    action: "draft.updated",
    category: "drafting",
    resourceType: "draft",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId", "version"],
  }),
  define({
    action: "draft.deleted",
    category: "drafting",
    resourceType: "draft",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId"],
  }),
  define({
    action: "draft_template.created",
    category: "drafting",
    resourceType: "draft_template",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["templateId", "category"],
  }),
  define({
    action: "draft_assist.created",
    category: "drafting",
    resourceType: "draft_assist",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId", "documentId", "task", "provider", "model", "status"],
  }),
  define({
    action: "draft_assist.async_queued",
    category: "drafting",
    resourceType: "draft_assist",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId", "documentId", "task", "provider", "jobId"],
  }),
  define({
    action: "draft_assist.reviewed",
    category: "drafting",
    resourceType: "draft_assist",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["draftId", "documentId", "decision", "status"],
  }),
  define({
    action: "ai_operational_proposal.async_queued",
    category: "operations",
    resourceType: "ai_proposal",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "draftId",
      "documentId",
      "proposalKinds",
      "proposalKindCount",
      "provider",
      "jobId",
    ],
  }),
  define({
    action: "ai_operational_proposal.created",
    category: "operations",
    resourceType: "ai_proposal",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "proposalId",
      "proposalKind",
      "sourceType",
      "draftId",
      "documentId",
      "provider",
      "model",
      "status",
    ],
  }),
  define({
    action: "ai_operational_proposal.reviewed",
    category: "operations",
    resourceType: "ai_proposal",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["proposalId", "proposalKind", "decision", "status"],
  }),
  define({
    action: "legal_research.artifact.created",
    category: "legal_research",
    resourceType: "legal_research",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "artifactId",
      "artifactKind",
      "status",
      "sourceReferenceCount",
      "contextLinkCount",
      "titleLength",
      "noteLength",
      "reviewOnly",
    ],
  }),
  define({
    action: "legal_research.artifact.updated",
    category: "legal_research",
    resourceType: "legal_research",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "artifactId",
      "artifactKind",
      "status",
      "sourceReferenceCount",
      "contextLinkCount",
      "titleLength",
      "noteLength",
      "reviewOnly",
    ],
  }),
  define({
    action: "legal_research.artifact.reviewed",
    category: "legal_research",
    resourceType: "legal_research",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["artifactId", "artifactKind", "decision", "status", "reviewOnly"],
  }),
  define({
    action: "time_entry.created",
    category: "billing",
    resourceType: "time_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "billing_rate_preset.created",
    category: "billing",
    resourceType: "billing_rate_preset",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "ratePresetId",
      "userId",
      "rateCents",
      "currency",
      "effectiveFrom",
      "effectiveTo",
    ],
  }),
  define({
    action: "billing_period_lock.created",
    category: "billing",
    resourceType: "billing_period_lock",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["billingPeriodLockId", "startsOn", "endsOn", "status"],
  }),
  define({
    action: "billing_period_lock.released",
    category: "billing",
    resourceType: "billing_period_lock",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["billingPeriodLockId", "startsOn", "endsOn", "status"],
  }),
  define({
    action: "time_entry.updated",
    category: "billing",
    resourceType: "time_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "time_entry.submitted",
    category: "billing",
    resourceType: "time_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "time_entry.approved",
    category: "billing",
    resourceType: "time_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "time_entry.written_off",
    category: "billing",
    resourceType: "time_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "expense_entry.created",
    category: "billing",
    resourceType: "expense_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "expense_entry.updated",
    category: "billing",
    resourceType: "expense_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "expense_entry.submitted",
    category: "billing",
    resourceType: "expense_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "expense_entry.approved",
    category: "billing",
    resourceType: "expense_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "expense_entry.written_off",
    category: "billing",
    resourceType: "expense_entry",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "invoice.created",
    category: "billing",
    resourceType: "invoice",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "invoice.approved",
    category: "billing",
    resourceType: "invoice",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "invoice.issued",
    category: "billing",
    resourceType: "invoice",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "invoice.voided",
    category: "billing",
    resourceType: "invoice",
    matterScope: "matter",
    actorHint: "authenticated_user",
  }),
  define({
    action: "billing_period_lock.created",
    category: "billing",
    resourceType: "billing_period_lock",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["billingPeriodLockId", "periodStart", "periodEnd", "reasonPresent"],
  }),
  define({
    action: "billing_rate_rule.created",
    category: "billing",
    resourceType: "billing_rate_rule",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "billingRateRuleId",
      "scope",
      "matterId",
      "userId",
      "role",
      "rateCents",
      "active",
    ],
  }),
  define({
    action: "billing_expense_category.created",
    category: "billing",
    resourceType: "billing_expense_category",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "billingExpenseCategoryId",
      "code",
      "active",
      "matterId",
      "practiceAreaCount",
      "jurisdictionCount",
      "reimbursableAllowed",
    ],
  }),
  define({
    action: "billing_expense_category.updated",
    category: "billing",
    resourceType: "billing_expense_category",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "billingExpenseCategoryId",
      "code",
      "active",
      "matterId",
      "practiceAreaCount",
      "jurisdictionCount",
      "reimbursableAllowed",
    ],
  }),
  define({
    action: "billing_export.requested",
    category: "billing",
    resourceType: "billing_export",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["jobId", "reportType", "reportScope", "idempotencyKeyPresent"],
  }),
  define({
    action: "manual_payment.created",
    category: "billing",
    resourceType: "manual_payment",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["invoiceId", "paymentId", "amountCents", "method", "evidencePresent"],
  }),
  define({
    action: "manual_payment.reconciled",
    category: "billing",
    resourceType: "manual_payment",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "invoiceId",
      "paymentId",
      "amountCents",
      "allocationCount",
      "evidencePresent",
    ],
  }),
  define({
    action: "hosted_payment_request.created",
    category: "billing",
    resourceType: "hosted_payment_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "paymentRequestId",
      "invoiceId",
      "amountCents",
      "status",
      "deliveryStatus",
      "reminderStatus",
      "paymentPlanStatus",
      "creditWriteOffStatus",
      "evidencePresent",
    ],
  }),
  define({
    action: "hosted_payment_request.state_updated",
    category: "billing",
    resourceType: "hosted_payment_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "paymentRequestId",
      "invoiceId",
      "previousStatus",
      "status",
      "deliveryStatus",
      "reminderStatus",
      "paymentPlanStatus",
      "creditWriteOffStatus",
      "evidencePresent",
    ],
  }),
  define({
    action: "hosted_payment_request.checkout_session_created",
    category: "billing",
    resourceType: "hosted_payment_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "paymentRequestId",
      "invoiceId",
      "provider",
      "checkoutSessionId",
      "checkoutUrlPresent",
      "amountCents",
      "status",
      "processorStatus",
    ],
  }),
  define({
    action: "payment_import_review_record.created",
    category: "billing",
    resourceType: "payment_import_review_record",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "paymentImportReviewRecordId",
      "providerLabel",
      "eventFamily",
      "eventStatus",
      "externalEventId",
      "externalPaymentIdPresent",
      "externalDepositIdPresent",
      "amountCents",
      "currency",
      "candidateInvoiceId",
      "candidateHostedPaymentRequestId",
      "candidateManualPaymentId",
      "duplicateCuePresent",
      "conflictReason",
      "reviewState",
      "refundChargebackReviewCueCategory",
      "refundChargebackReviewCueStatus",
      "refundChargebackReviewAction",
      "rawProviderPayloadRetained",
      "invoiceBalanceMutation",
      "settlementAutomation",
      "reconciliationMutation",
      "refundHandling",
      "chargebackHandling",
      "trustPosting",
      "providerCommand",
      "clientNotification",
    ],
  }),
  define({
    action: "payment_import_deposit_match_review.recorded",
    category: "billing",
    resourceType: "payment_import_deposit_match_review",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "paymentImportDepositMatchReviewId",
      "paymentImportReviewRecordId",
      "candidateManualPaymentId",
      "candidateInvoiceId",
      "decision",
      "reason",
      "importAmountCents",
      "manualPaymentAmountCents",
      "currency",
      "candidateManualPaymentStatus",
      "reviewerEvidencePresent",
      "idempotencyKeyPresent",
      "rawProviderPayloadRetained",
      "invoiceBalanceMutation",
      "settlementAutomation",
      "reconciliationMutation",
      "refundHandling",
      "chargebackHandling",
      "trustPosting",
      "providerCommand",
      "clientNotification",
      "depositMatching",
    ],
  }),
  define({
    action: "billing_export.requested",
    category: "billing",
    resourceType: "billing_export",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "exportKind",
      "recordCount",
      "timeEntryCount",
      "expenseEntryCount",
      "invoiceCount",
      "paymentCount",
      "enqueueStatus",
    ],
  }),
  define({
    action: "staff_report_export.requested",
    category: "operations",
    resourceType: "staff_report_export",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "reportType",
      "reportDefinitionKey",
      "exportProfileId",
      "groupingKey",
      "idempotencyKeyPresent",
      "enqueueStatus",
    ],
  }),
  define({
    action: "trust_transfer_request.created",
    category: "trust",
    resourceType: "trust_transfer_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["trustTransferRequestId", "invoiceId", "amountCents", "status"],
  }),
  define({
    action: "trust_transfer_request.approved",
    category: "trust",
    resourceType: "trust_transfer_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "trustTransferRequestId",
      "invoiceId",
      "amountCents",
      "status",
      "previousStatus",
      "invoiceBalanceDueCents",
      "availableTrustBalanceCents",
      "evidencePresent",
    ],
  }),
  define({
    action: "trust_transfer_request.rejected",
    category: "trust",
    resourceType: "trust_transfer_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "trustTransferRequestId",
      "invoiceId",
      "amountCents",
      "status",
      "previousStatus",
      "evidencePresent",
    ],
  }),
  define({
    action: "trust_transfer_request.linked",
    category: "trust",
    resourceType: "trust_transfer_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "trustTransferRequestId",
      "invoiceId",
      "ledgerTransactionId",
      "amountCents",
      "status",
      "previousStatus",
      "trustAssetCreditCents",
      "clientLiabilityDebitCents",
      "evidencePresent",
    ],
  }),
  define({
    action: "ledger.posting_request.prepared",
    category: "trust",
    resourceType: "ledger_posting_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "postingRequestId",
      "transactionId",
      "matterIds",
      "accountIds",
      "status",
      "entryCount",
      "idempotencyKeyPresent",
      "preparationNotesPresent",
    ],
  }),
  define({
    action: "ledger.posting_request.approved",
    category: "trust",
    resourceType: "ledger_posting_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "postingRequestId",
      "transactionId",
      "ledgerTransactionId",
      "matterIds",
      "accountIds",
      "previousStatus",
      "status",
      "reviewNotesPresent",
    ],
  }),
  define({
    action: "ledger.posting_request.rejected",
    category: "trust",
    resourceType: "ledger_posting_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "postingRequestId",
      "transactionId",
      "matterIds",
      "accountIds",
      "previousStatus",
      "status",
      "reviewNotesPresent",
      "rejectionReasonPresent",
    ],
  }),
  define({
    action: "trust_export.requested",
    category: "trust",
    resourceType: "trust_export",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "exportKind",
      "recordCount",
      "trustTransferRequestCount",
      "ledgerAccountCount",
      "ledgerEntryCount",
      "balanceCount",
      "trustBalanceCount",
      "enqueueStatus",
    ],
  }),
  define({
    action: "ledger.transaction.posted",
    category: "trust",
    resourceType: "ledger_transaction",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: WORKFLOW_RESOURCE_KEYS,
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "jurisdictional_trust_export.requested",
    category: "trust",
    resourceType: "jurisdictional_trust_export",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "jobId",
      "reportType",
      "reportScope",
      "jurisdiction",
      "idempotencyKeyPresent",
    ],
  }),
  define({
    action: "ledger.transaction_approval.decided",
    category: "trust",
    resourceType: "ledger_transaction_approval",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["transactionId", "decision", "status"],
  }),
  define({
    action: "ledger.reconciliation.created",
    category: "trust",
    resourceType: "ledger_reconciliation",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["accountId", "statementDate", "balanced"],
  }),
  define({
    action: "ledger.reconciliation_exception_resolution.recorded",
    category: "trust",
    resourceType: "ledger_reconciliation_exception_resolution",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "accountId",
      "statementRowId",
      "varianceDecision",
      "resolutionNotePresent",
    ],
  }),
  define({
    action: "ledger.statement_import_batch.recorded",
    category: "trust",
    resourceType: "ledger_statement_import_batch",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "accountId",
      "importedStatementRowCount",
      "duplicateStatementRowCount",
      "status",
      "sourceLabelPresent",
      "checksumPresent",
      "matchingProfilePresent",
    ],
  }),
  define({
    action: "ledger.statement_match_rule_profile.recorded",
    category: "trust",
    resourceType: "ledger_statement_match_rule_profile",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "accountId",
      "referenceStrategy",
      "descriptionStrategy",
      "dateWindowDays",
      "amountToleranceCents",
      "varianceCategoryCount",
      "reviewerExplanationRequired",
      "reviewOnly",
    ],
  }),
  define({
    action: "ledger.accounting_review_profile.recorded",
    category: "trust",
    resourceType: "ledger_accounting_review_profile",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "accountId",
      "accountType",
      "boundaryPosture",
      "protectedFunds",
      "bankFeedImportStatus",
      "bankFeedSourceLabelPresent",
      "automaticMatching",
      "vendorTracking",
      "expenseCategoryTracking",
      "clientMatterTracking",
      "reviewOnly",
    ],
  }),
  define({
    action: "contact.data_quality_resolution.recorded",
    category: "contacts",
    resourceType: "contact_data_quality_resolution",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    matterMetadataKeys: ["matterId"],
    resourceMetadataKeys: [
      "contactId",
      "signalKind",
      "decision",
      "relatedContactPresent",
      "sourceRecordPresent",
      "resolutionNotePresent",
    ],
  }),
  define({
    action: "email_outbox.queued",
    category: "communications",
    resourceType: "email_outbox",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["emailId", "jobId", "recipientCount", "templateKey", "provider"],
  }),
  define({
    action: "email_outbox.manual_retry",
    category: "communications",
    resourceType: "email_outbox",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: WORKFLOW_RESOURCE_KEYS,
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "email.settings_updated",
    category: "communications",
    resourceType: "provider_setting",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["kind", "provider", "enabled", "passwordConfigured"],
  }),
  define({
    action: "email_template_draft.created",
    category: "communications",
    resourceType: "email_template_draft",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "templateDraftId",
      "category",
      "status",
      "version",
      "subjectLength",
      "textLength",
      "htmlLength",
      "recipientHintCount",
      "draftAndPreviewOnly",
      "providerNeutral",
    ],
  }),
  define({
    action: "email_template_draft.updated",
    category: "communications",
    resourceType: "email_template_draft",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "templateDraftId",
      "category",
      "status",
      "version",
      "subjectLength",
      "textLength",
      "htmlLength",
      "recipientHintCount",
      "draftAndPreviewOnly",
      "providerNeutral",
    ],
  }),
  define({
    action: "email_template_published_version.created",
    category: "communications",
    resourceType: "email_template_published_version",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "publishedVersionId",
      "templateDraftId",
      "version",
      "draftVersion",
      "publishedAt",
      "subjectLength",
      "textLength",
      "htmlLength",
      "recipientHintCount",
      "providerNeutral",
      "deliveryQueued",
      "providerDeliverySideEffect",
      "campaignAutomation",
      "bulkSend",
    ],
  }),
  define({
    action: "email_template_preview_snapshot.created",
    category: "communications",
    resourceType: "email_template_preview_snapshot",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "templateDraftId",
      "previewSnapshotId",
      "recipientCount",
      "warningCount",
      "persisted",
      "queued",
      "providerNeutral",
    ],
  }),
  define({
    action: "email_receipt_link.created",
    category: "communications",
    resourceType: "email_receipt_link",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["emailId", "receiptLinkId", "purpose", "expiresAt"],
    actorMetadataKeys: ["actorId", "actorType"],
  }),
  define({
    action: "connector.created",
    category: "operations",
    resourceType: "connector",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "connectorId",
      "connectorType",
      "connectorKey",
      "status",
      "secretReferencePresent",
    ],
  }),
  define({
    action: "connector.updated",
    category: "operations",
    resourceType: "connector",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "connectorId",
      "connectorType",
      "connectorKey",
      "status",
      "secretReferencePresent",
      "secretReferenceChanged",
    ],
  }),
  define({
    action: "connector_outbox.queued",
    category: "operations",
    resourceType: "connector_outbox",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "connectorId",
      "connectorType",
      "eventType",
      "idempotencyKeyPresent",
      "resourceType",
      "resourceId",
    ],
  }),
  define({
    action: "connector_outbox.manual_retry",
    category: "operations",
    resourceType: "connector_outbox",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "connectorId",
      "connectorType",
      "connectorKey",
      "outboxId",
      "eventType",
      "resourceType",
      "resourceId",
      "beforeStatus",
      "expectedStatus",
      "afterStatus",
      "attemptCount",
      "maxAttempts",
      "idempotencyKeyPresent",
      "deliveryJobQueued",
      "queueName",
    ],
  }),
  define({
    action: "connector_outbox.manual_dead_letter",
    category: "operations",
    resourceType: "connector_outbox",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "connectorId",
      "connectorType",
      "connectorKey",
      "outboxId",
      "eventType",
      "resourceType",
      "resourceId",
      "beforeStatus",
      "expectedStatus",
      "afterStatus",
      "attemptCount",
      "maxAttempts",
      "idempotencyKeyPresent",
      "deliveryJobQueued",
      "queueName",
    ],
  }),
  define({
    action: "integration_developer_app.registered",
    category: "operations",
    resourceType: "integration_developer_app",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "appId",
      "connectorId",
      "connectorType",
      "connectorKey",
      "status",
      "scopeCount",
      "redirectUriCount",
      "allowedOriginCount",
      "endpointRegion",
      "endpointBaseUrlPresent",
      "rateLimitWindowSeconds",
      "rateLimitMaxRequests",
      "rateLimitEnforcement",
      "customActionCount",
    ],
  }),
  define({
    action: "integration_api_credential.created",
    category: "operations",
    resourceType: "integration_api_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "appId",
      "credentialId",
      "connectorId",
      "scopeCount",
      "secretReferencePresent",
      "expiresAtPresent",
    ],
  }),
  define({
    action: "integration_api_credential.revoked",
    category: "operations",
    resourceType: "integration_api_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["appId", "credentialId", "revokedAt"],
  }),
  define({
    action: "integration_webhook_subscription.created",
    category: "operations",
    resourceType: "integration_webhook_subscription",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "appId",
      "connectorId",
      "subscriptionId",
      "status",
      "eventCount",
      "destinationHost",
      "signingSecretReferencePresent",
    ],
  }),
  define({
    action: "task.created",
    category: "operations",
    resourceType: "task",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "taskId",
      "assignedToUserId",
      "priority",
      "dueAt",
      "sourceType",
      "sourceId",
    ],
  }),
  define({
    action: "task.updated",
    category: "operations",
    resourceType: "task",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "taskId",
      "assignedToUserId",
      "priority",
      "dueAt",
      "sourceType",
      "sourceId",
      "titleChanged",
      "descriptionChanged",
      "assignmentChanged",
      "dueAtChanged",
      "sourceChanged",
    ],
  }),
  define({
    action: "task.completed",
    category: "operations",
    resourceType: "task",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["taskId", "assignedToUserId", "completedByUserId"],
  }),
  define({
    action: "task.reopened",
    category: "operations",
    resourceType: "task",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["taskId", "assignedToUserId", "reopenedByUserId"],
  }),
  define({
    action: "task.archived",
    category: "operations",
    resourceType: "task",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["taskId", "assignedToUserId", "archivedByUserId"],
  }),
  define({
    action: "outbound_webhook.test_delivery_simulated",
    category: "outbound_webhooks",
    resourceType: "outbound_webhook",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "deliveryId",
      "eventCount",
      "events",
      "destinationScheme",
      "destinationHost",
      "destinationPort",
      "signingAlgorithm",
      "signatureHeader",
      "simulationOnly",
    ],
  }),
  define({
    action: "inbound_email.triage_updated",
    category: "communications",
    resourceType: "inbound_email",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    matterMetadataKeys: ["matterId", "previousMatterId"],
    resourceMetadataKeys: [
      "status",
      "labelCount",
      "staffTriageStatus",
      "assignedToUserId",
      "contactIds",
      "privateNoteAdded",
      "privateNoteCount",
      "followUpChannel",
      "followUpConsentStatus",
      "followUpDueAt",
    ],
  }),
  define({
    action: "inbound_email.matter_draft.confirmed",
    category: "communications",
    resourceType: "inbound_email",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "sourceMessageId",
      "providerMessageIdPresent",
      "receivedAt",
      "recipientCount",
      "attachmentCount",
      "subjectPresent",
      "redactedSummaryLength",
      "proposedTitleLength",
      "proposedPracticeArea",
      "proposedJurisdiction",
      "clientKind",
      "automaticMatterCreation",
    ],
  }),
  define({
    action: "inbound_email.parser_job.manual_retry",
    category: "communications",
    resourceType: "inbound_email",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "retryJobId",
      "queueName",
      "jobName",
      "beforeStatus",
      "expectedStatus",
      "afterStatus",
      "provider",
      "source",
      "idempotencyKeyPresent",
      "retryJobQueued",
    ],
  }),
  define({
    action: "inbound_email.parser_job.manual_dead_letter",
    category: "communications",
    resourceType: "inbound_email",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "queueName",
      "jobName",
      "beforeStatus",
      "expectedStatus",
      "afterStatus",
      "provider",
      "source",
      "idempotencyKeyPresent",
      "retryJobQueued",
    ],
  }),
  define({
    action: "inbound_email.parser_job.replay_requested",
    category: "communications",
    resourceType: "inbound_email",
    matterScope: "firm",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "jobId",
      "queueName",
      "jobName",
      "expectedStatus",
      "currentStatus",
      "provider",
      "source",
      "idempotencyKeyPresent",
      "reviewOnly",
      "requestType",
      "reviewState",
      "redactedAuthorizedProjection",
    ],
  }),
  define({
    action: "inbound_email.imap_settings_updated",
    category: "communications",
    resourceType: "provider_setting",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["kind", "provider", "enabled", "passwordConfigured", "pollQueued"],
  }),
  define({
    action: "inbound_email.imap_poll_requested",
    category: "communications",
    resourceType: "provider_setting",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["provider", "pollQueued"],
  }),
  define({
    action: "inbound_email.attachment.promoted_to_document",
    category: "communications",
    resourceType: "document",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["messageId", "attachmentId", "documentId"],
  }),
  define({
    action: "calendar.event.created",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "uid", "status", "attendeeCount"],
  }),
  define({
    action: "calendar.event.updated",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "uid",
      "scope",
      "clientContactId",
      "status",
      "sequence",
      "attendeeCount",
      "reminderCount",
      "meetingLinkMode",
      "meetingProviderKey",
      "hasMeetingLink",
      "startsAtChanged",
      "endsAtChanged",
      "source",
      "credentialId",
    ],
  }),
  define({
    action: "calendar.scheduling_request.created",
    category: "calendar",
    resourceType: "calendar_scheduling_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "status",
      "kind",
      "sourceType",
      "ownerUserId",
      "privacy",
      "hasRequestedDueAt",
      "hasRequestedStartsAt",
      "hasRequestedEndsAt",
      "taskId",
      "calendarEventId",
      "calendarReminderId",
    ],
  }),
  define({
    action: "calendar.scheduling_request.reviewed",
    category: "calendar",
    resourceType: "calendar_scheduling_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "status",
      "kind",
      "sourceType",
      "ownerUserId",
      "privacy",
      "hasRequestedDueAt",
      "hasRequestedStartsAt",
      "hasRequestedEndsAt",
      "taskId",
      "calendarEventId",
      "calendarReminderId",
    ],
  }),
  define({
    action: "calendar.scheduling_request.aging_review_recorded",
    category: "calendar",
    resourceType: "calendar_scheduling_request",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "decision",
      "cueStatus",
      "ageHours",
      "automaticFinalConfirmation",
      "autoExpires",
      "providerSync",
      "publicRoomCreated",
      "nativeMediaCreated",
      "chatCreated",
      "recordingCreated",
      "matterCreated",
      "taskCreated",
      "eventCreated",
      "eventRescheduled",
      "reminderCancelled",
    ],
  }),
  define({
    action: "appointment_booking.profile.upserted",
    category: "calendar",
    resourceType: "appointment_booking_profile",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["profileId", "status", "windowCount", "durationMinutes"],
  }),
  define({
    action: "appointment_booking.link.created",
    category: "calendar",
    resourceType: "appointment_booking_link",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: [
      "profileId",
      "linkId",
      "expiresAt",
      "matterLinked",
      "clientContactLinked",
    ],
  }),
  define({
    action: "appointment_booking.hold.created",
    category: "calendar",
    resourceType: "appointment_booking_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "profileId",
      "linkId",
      "eventId",
      "source",
      "status",
      "matterLinked",
      "clientContactLinked",
      "attendeeAdded",
      "sourceUrlPresent",
      "opposingPartyCount",
      "hasRequesterEmail",
      "hasRequesterTelephone",
    ],
  }),
  define({
    action: "appointment_booking.hold.reviewed",
    category: "calendar",
    resourceType: "appointment_booking_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "profileId",
      "eventId",
      "reviewStatus",
      "eventStatus",
      "source",
      "matterLinked",
    ],
  }),
  define({
    action: "appointment_booking.hold.aging_review_recorded",
    category: "calendar",
    resourceType: "appointment_booking_request",
    matterScope: "optional_matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "requestId",
      "profileId",
      "eventId",
      "decision",
      "cueStatus",
      "ageHours",
      "automaticFinalConfirmation",
      "autoExpires",
      "providerSync",
      "publicRoomCreated",
      "nativeMediaCreated",
      "chatCreated",
      "recordingCreated",
      "matterCreated",
    ],
  }),
  define({
    action: "calendar.event.cancelled",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "uid", "status", "previousStatus", "sequence"],
  }),
  define({
    action: "calendar.event.rescheduled",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "uid", "status", "startsAtChanged", "endsAtChanged"],
  }),
  define({
    action: "calendar.event.deleted",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "uid"],
  }),
  define({
    action: "calendar.attendee.created",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "attendeeId", "role", "responseStatus"],
  }),
  define({
    action: "calendar.attendee.updated",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "attendeeId", "role", "responseStatus"],
  }),
  define({
    action: "calendar.attendee.deleted",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "attendeeId"],
  }),
  define({
    action: "calendar.invitation.queued",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "attendeeId",
      "attendeeCount",
      "invitationStatus",
      "emailId",
      "jobId",
      "requestedMeetingLink",
      "meetingLinkMode",
      "meetingLinkIncluded",
      "meetingProviderKey",
      "requestedGuestAccessToken",
      "meetingLinksStatus",
      "meetingLinksReason",
      "meetingLinksProvider",
      "guestAccessStatus",
      "guestAccessReason",
      "guestAccessProvider",
      "invitationEmailStatus",
      "invitationEmailReason",
      "invitationEmailProvider",
      "meetingBoundary",
    ],
  }),
  define({
    action: "calendar.invitation.skipped",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "attendeeId",
      "attendeeCount",
      "invitationStatus",
      "emailId",
      "jobId",
      "requestedMeetingLink",
      "meetingLinkMode",
      "meetingLinkIncluded",
      "meetingProviderKey",
      "requestedGuestAccessToken",
      "meetingLinksStatus",
      "meetingLinksReason",
      "meetingLinksProvider",
      "guestAccessStatus",
      "guestAccessReason",
      "guestAccessProvider",
      "invitationEmailStatus",
      "invitationEmailReason",
      "invitationEmailProvider",
      "reason",
      "meetingBoundary",
    ],
  }),
  define({
    action: "calendar.reminder.created",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "reminderId", "channel", "status"],
  }),
  define({
    action: "calendar.reminder.updated",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "reminderId", "channel", "status"],
  }),
  define({
    action: "calendar.reminder.queued",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "reminderId",
      "channel",
      "status",
      "notificationStatus",
      "emailId",
      "jobId",
      "deliveryDelayMs",
    ],
  }),
  define({
    action: "calendar.reminder.skipped",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "reminderId",
      "channel",
      "status",
      "notificationStatus",
      "notificationReason",
    ],
  }),
  define({
    action: "calendar.reminder.reconciled",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "reminderId",
      "channel",
      "status",
      "reconciliationReason",
      "cancelledEmailCount",
      "skippedJobCount",
    ],
  }),
  define({
    action: "calendar.reminder.deleted",
    category: "calendar",
    resourceType: "calendar_event",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["eventId", "reminderId"],
  }),
  define({
    action: "calendar.meeting_session.created",
    category: "calendar",
    resourceType: "calendar_meeting_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "status",
      "endedAt",
      "retentionUntil",
      "issuedCount",
      "waitingCount",
      "admittedCount",
      "deniedCount",
      "revokedCount",
    ],
  }),
  define({
    action: "calendar.meeting_session.updated",
    category: "calendar",
    resourceType: "calendar_meeting_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "status",
      "endedAt",
      "retentionUntil",
      "issuedCount",
      "waitingCount",
      "admittedCount",
      "deniedCount",
      "revokedCount",
    ],
  }),
  define({
    action: "calendar.meeting_session.ended",
    category: "calendar",
    resourceType: "calendar_meeting_session",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "status",
      "endedAt",
      "retentionUntil",
      "issuedCount",
      "waitingCount",
      "admittedCount",
      "deniedCount",
      "revokedCount",
    ],
  }),
  define({
    action: "calendar.guest_link.created",
    category: "calendar",
    resourceType: "calendar_guest_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "linkId",
      "status",
      "expiresAt",
      "checkedInAt",
      "admittedAt",
      "deniedAt",
      "revokedAt",
      "retentionUntil",
    ],
  }),
  define({
    action: "calendar.guest_link.updated",
    category: "calendar",
    resourceType: "calendar_guest_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "linkId",
      "status",
      "expiresAt",
      "checkedInAt",
      "admittedAt",
      "deniedAt",
      "revokedAt",
      "retentionUntil",
    ],
  }),
  define({
    action: "calendar.guest_link.revoked",
    category: "calendar",
    resourceType: "calendar_guest_link",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "eventId",
      "sessionId",
      "linkId",
      "status",
      "expiresAt",
      "checkedInAt",
      "admittedAt",
      "deniedAt",
      "revokedAt",
      "retentionUntil",
    ],
  }),
  define({
    action: "calendar.credential.created",
    category: "calendar",
    resourceType: "calendar_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["credentialId", "label"],
  }),
  define({
    action: "calendar.credential.revoked",
    category: "calendar",
    resourceType: "calendar_credential",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["credentialId", "revokedAt"],
  }),
  define({
    action: "conversation_thread.created",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
    ],
  }),
  define({
    action: "conversation_thread.closed",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
      "lifecycleAction",
    ],
  }),
  define({
    action: "conversation_thread.reopened",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
      "lifecycleAction",
    ],
  }),
  define({
    action: "conversation_thread.access_revoked",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
      "lifecycleAction",
    ],
  }),
  define({
    action: "conversation_thread.export_requested",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
      "lifecycleAction",
    ],
  }),
  define({
    action: "conversation_thread.export_artifact_requested",
    category: "communications",
    resourceType: "conversation_thread",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "threadId",
      "status",
      "exportState",
      "retentionBoundary",
      "notificationBoundary",
      "accessRevoked",
      "jobId",
      "reportType",
      "reportScope",
      "messageCount",
      "idempotencyKeyPresent",
      "enqueueStatus",
    ],
  }),
  define({
    action: "conversation_message.created",
    category: "communications",
    resourceType: "conversation_message",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: [
      "messageId",
      "threadId",
      "kind",
      "bodyLength",
      "authoredByUserIdPresent",
      "notificationBoundary",
      "notificationCount",
      "unreadNotificationCount",
      "mutedNotificationCount",
    ],
  }),
  define({
    action: "legal_clinic.program.created",
    category: "legal_clinic",
    resourceType: "legal_clinic_program",
    matterScope: "firm",
    actorHint: "authenticated_user",
    matterMetadataKeys: [],
    resourceMetadataKeys: ["programId", "referralPathCount", "eligibilityRuleCount"],
  }),
  define({
    action: "legal_clinic.profile.upserted",
    category: "legal_clinic",
    resourceType: "legal_clinic_matter_profile",
    matterScope: "matter",
    actorHint: "authenticated_user",
    resourceMetadataKeys: ["programId", "referralStatus", "eligibilityStatus"],
  }),
] as const satisfies readonly AuditEventTaxonomyDefinition[];

const definitionsByAction = new Map(
  auditEventTaxonomyDefinitions.map((definition) => [definition.action, definition]),
);

const definitionsByActionAndResource = new Map(
  auditEventTaxonomyDefinitions
    .filter((definition) => definition.resourceType)
    .map((definition) => [`${definition.action}:${definition.resourceType}`, definition]),
);

function definitionFor(event: Pick<AuditEvent, "action" | "resourceType">) {
  return (
    definitionsByActionAndResource.get(`${event.action}:${event.resourceType}`) ??
    definitionsByAction.get(event.action)
  );
}

function hasStringMetadata(metadata: Record<string, unknown>, keys: readonly string[]): boolean {
  return keys.some((key) => typeof metadata[key] === "string" && metadata[key].length > 0);
}

function hasMatterId(event: AuditEvent, definition: AuditEventTaxonomyDefinition): boolean {
  if (event.resourceType === "matter" && event.resourceId.length > 0) return true;
  return hasStringMetadata(event.metadata, definition.matterMetadataKeys);
}

export function classifyAuditEvent(event: AuditEvent): AuditEventClassification {
  const definition = definitionFor(event);
  if (!definition) {
    return {
      action: event.action,
      category: "unknown",
      known: false,
      resourceType: event.resourceType,
      matterScope: "derived",
      actorHint: "unknown",
      metadataHints: { matter: [], resource: [], actor: [] },
      hasMatterId: false,
      resourceTypeMatches: true,
    };
  }

  return {
    action: event.action,
    category: definition.category,
    known: true,
    expectedResourceType: definition.resourceType,
    resourceType: event.resourceType,
    matterScope: definition.matterScope,
    actorHint: definition.actorHint,
    metadataHints: {
      matter: definition.matterMetadataKeys,
      resource: definition.resourceMetadataKeys,
      actor: definition.actorMetadataKeys,
    },
    hasMatterId: hasMatterId(event, definition),
    resourceTypeMatches: !definition.resourceType || definition.resourceType === event.resourceType,
  };
}

function increment<T extends string>(record: Partial<Record<T, number>>, key: T): void {
  record[key] = (record[key] ?? 0) + 1;
}

export function summarizeAuditEventTaxonomy(
  events: readonly AuditEvent[],
): AuditEventTaxonomySummary {
  const byCategory: Partial<Record<AuditEventCategory, number>> = {};
  const byMatterScope: Partial<Record<AuditMatterScopeHint, number>> = {};
  const byActorHint: Partial<Record<AuditActorHint, number>> = {};
  const unknownActions = new Set<string>();
  const mismatches = new Map<
    string,
    {
      action: string;
      expectedResourceType: string;
      observedResourceType: string;
      count: number;
    }
  >();
  let known = 0;
  let matterScopedWithoutMatterId = 0;

  for (const event of events) {
    const classification = classifyAuditEvent(event);
    if (classification.known) {
      known += 1;
    } else {
      unknownActions.add(classification.action);
    }
    increment(byCategory, classification.category);
    increment(byMatterScope, classification.matterScope);
    increment(byActorHint, classification.actorHint);

    if (classification.matterScope === "matter" && !classification.hasMatterId) {
      matterScopedWithoutMatterId += 1;
    }

    if (!classification.resourceTypeMatches && classification.expectedResourceType) {
      const key = `${classification.action}:${classification.expectedResourceType}:${classification.resourceType}`;
      const existing = mismatches.get(key);
      if (existing) {
        existing.count += 1;
      } else {
        mismatches.set(key, {
          action: classification.action,
          expectedResourceType: classification.expectedResourceType,
          observedResourceType: classification.resourceType,
          count: 1,
        });
      }
    }
  }

  return {
    total: events.length,
    known,
    unknown: events.length - known,
    byCategory,
    byMatterScope,
    byActorHint,
    matterScopedWithoutMatterId,
    resourceTypeMismatches: [...mismatches.values()].sort((left, right) =>
      left.action.localeCompare(right.action),
    ),
    unknownActions: [...unknownActions].sort(),
  };
}
