import type { Action, ResourceKind } from "./permissions.js";

export type AuthorizationFixtureFamily =
  | "matter"
  | "contact"
  | "document"
  | "job"
  | "ai_proposal"
  | "payment_import_review"
  | "payment_import_deposit_match_review"
  | "payment_import_refund_chargeback_review"
  | "trust_transfer_review"
  | "staff_report_export"
  | "audit_export"
  | "billing_export"
  | "jurisdictional_trust_export"
  | "portal_link";

export type AuthorizationFixtureRelation =
  | "firm_wide_reviewer"
  | "auditor_reviewer"
  | "billing_bookkeeper"
  | "assigned_matter_staff"
  | "unassigned_matter_staff"
  | "standalone_contact_creator"
  | "external_portal_contact"
  | "account_bound_portal_grant_holder"
  | "public_share_token_holder"
  | "expired_public_share_token_holder"
  | "revoked_public_share_token_holder"
  | "unverified_public_share_token_holder";

export type AuthorizationFixtureDecision = "allow" | "deny";

export interface AuthorizationFixtureCase {
  id: string;
  family: AuthorizationFixtureFamily;
  resource: ResourceKind;
  action: Action;
  relation: AuthorizationFixtureRelation;
  expectedDecision: AuthorizationFixtureDecision;
  listVisible: boolean;
  subjectId: string;
  matterId?: string;
  contactId?: string;
  resourceId?: string;
  rationale: string;
}

export const authorizationRelationVocabulary: Record<AuthorizationFixtureRelation, string> = {
  firm_wide_reviewer:
    "Owner administrators and auditors can review firm-wide records without matter assignment.",
  auditor_reviewer:
    "Auditors can read and export firm-wide review records without receiving mutation authority.",
  billing_bookkeeper:
    "Billing bookkeepers can read and export financial records without approving trust-transfer review commands.",
  assigned_matter_staff:
    "Staff with a role permission and matching matter assignment can see matter-scoped records.",
  unassigned_matter_staff:
    "Staff with a role permission but no matching assignment cannot see matter-scoped records.",
  standalone_contact_creator:
    "Staff can list their own unlinked standalone contacts without widening matter-scoped records.",
  external_portal_contact:
    "Client-external users are limited to active portal grants for their contact and matter.",
  account_bound_portal_grant_holder:
    "Client portal file visibility requires an active grant bound to the portal account.",
  public_share_token_holder:
    "Valid public share tokens expose only safe document metadata for the linked matter.",
  expired_public_share_token_holder:
    "Expired public share tokens are hidden and logged as denied public access.",
  revoked_public_share_token_holder:
    "Revoked public share tokens are hidden and logged as denied public access.",
  unverified_public_share_token_holder:
    "Email-verified share links deny public reads until verification completes.",
};

export const authorizationFixtureCases: AuthorizationFixtureCase[] = [
  {
    id: "matter:firm-wide:list-all",
    family: "matter",
    resource: "matter",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    rationale: "Firm-wide reviewers can list the full synthetic matter set.",
  },
  {
    id: "matter:assigned:list-visible",
    family: "matter",
    resource: "matter",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "matter-001",
    rationale: "Assigned staff can read and list their assigned matter.",
  },
  {
    id: "matter:unassigned:list-hidden",
    family: "matter",
    resource: "matter",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "matter-002",
    rationale: "Matter-scoped staff cannot read or list unassigned matter records.",
  },
  {
    id: "contact:firm-wide:list-all",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    resourceId: "contact-northstar",
    rationale: "Firm-wide reviewers can list all synthetic contact dossiers.",
  },
  {
    id: "contact:assigned:client-visible",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "contact-ada",
    rationale: "Assigned staff can list the client contact linked through their visible matter.",
  },
  {
    id: "contact:assigned:counterparty-visible",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "contact-river",
    rationale:
      "Assigned staff can list the counterparty contact linked through their visible matter.",
  },
  {
    id: "contact:unassigned:list-hidden",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "allow",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "contact-northstar",
    rationale:
      "Staff with route-level contact read access do not list contacts linked only to unassigned matters.",
  },
  {
    id: "contact:standalone-creator:list-visible",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "standalone_contact_creator",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-staff",
    resourceId: "contact-standalone-creator",
    rationale: "Staff can list their own standalone contact when it is not linked to a matter.",
  },
  {
    id: "contact:portal-client:staff-list-denied",
    family: "contact",
    resource: "contact",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "contact-ada",
    rationale: "Client-external portal users cannot access staff contact dossier/list routes.",
  },
  {
    id: "document:assigned:read-visible",
    family: "document",
    resource: "document",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "doc-shareable-001",
    rationale: "Assigned staff can read matter documents through existing matter-scope checks.",
  },
  {
    id: "document:unassigned:read-hidden",
    family: "document",
    resource: "document",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "doc-hidden-002",
    rationale: "Documents inherit matter-scope visibility and are hidden outside assignment.",
  },
  {
    id: "document:portal-grant:metadata-visible",
    family: "document",
    resource: "document",
    action: "read",
    relation: "account_bound_portal_grant_holder",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "doc-portal-visible-001",
    rationale: "Account-bound portal grants expose only explicit per-file metadata.",
  },
  {
    id: "job:firm-wide:no-matter-visible",
    family: "job",
    resource: "job",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    resourceId: "job-firm-wide-report",
    rationale: "Firm-wide reviewers can inspect redacted lifecycle jobs without matter metadata.",
  },
  {
    id: "job:assigned:matter-job-visible",
    family: "job",
    resource: "job",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "job-assigned",
    rationale: "Matter-scoped staff can list jobs whose safe metadata names an assigned matter.",
  },
  {
    id: "job:unassigned:matter-job-hidden",
    family: "job",
    resource: "job",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "job-unassigned",
    rationale: "Matter-scoped job lists skip jobs for unassigned matters instead of leaking them.",
  },
  {
    id: "job:unassigned:no-matter-hidden",
    family: "job",
    resource: "job",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    resourceId: "job-firm-wide-report",
    rationale: "Non-admin job readers do not see jobs that lack safe matter metadata.",
  },
  {
    id: "ai-proposal:firm-wide:list-all",
    family: "ai_proposal",
    resource: "ai_proposal",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    resourceId: "ai-proposal-matter-002",
    rationale: "Firm-wide reviewers can list synthetic AI proposal records across matters.",
  },
  {
    id: "ai-proposal:assigned:list-visible",
    family: "ai_proposal",
    resource: "ai_proposal",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "ai-proposal-deadline-001",
    rationale: "Assigned staff can list AI proposal records linked to their assigned matter.",
  },
  {
    id: "ai-proposal:unassigned:list-hidden",
    family: "ai_proposal",
    resource: "ai_proposal",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "ai-proposal-matter-002",
    rationale:
      "Matter-scoped staff cannot query or list AI proposal records linked only to unassigned matters.",
  },
  {
    id: "ai-proposal:portal-client:staff-list-denied",
    family: "ai_proposal",
    resource: "ai_proposal",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "ai-proposal-deadline-001",
    rationale: "Client-external portal users cannot access staff AI proposal list routes.",
  },
  {
    id: "payment-import-review:firm-wide:list-all",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    resourceId: "payment-import-review-auth-unassigned",
    rationale: "Firm-wide reviewers can list synthetic payment import review records.",
  },
  {
    id: "payment-import-review:assigned:list-visible",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "payment-import-review-auth-assigned",
    rationale: "Assigned staff can list payment import review records for their matter.",
  },
  {
    id: "payment-import-review:unassigned:list-hidden",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "payment-import-review-auth-unassigned",
    rationale: "Matter-scoped staff cannot query unassigned payment import review records.",
  },
  {
    id: "payment-import-review:portal-client:staff-list-denied",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "payment-import-review-auth-assigned",
    rationale: "Client-external portal users cannot access staff payment import review lists.",
  },
  {
    id: "payment-import-review:firm-wide:create",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "create",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    matterId: "matter-002",
    resourceId: "payment-import-review-auth-firm-wide-create",
    rationale: "Firm-wide reviewers can create synthetic payment import review records.",
  },
  {
    id: "payment-import-review:assigned:create",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "create",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "payment-import-review-auth-assigned-create",
    rationale: "Assigned staff can create payment import review records for their matter.",
  },
  {
    id: "payment-import-review:unassigned:create-denied",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "create",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "payment-import-review-auth-unassigned-create",
    rationale: "Matter-scoped staff cannot create payment import review records elsewhere.",
  },
  {
    id: "payment-import-review:portal-client:create-denied",
    family: "payment_import_review",
    resource: "expense_entry",
    action: "create",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "payment-import-review-auth-portal-create",
    rationale: "Client-external portal users cannot create staff payment import review records.",
  },
  {
    id: "deposit-match-review:firm-wide:list-all",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "read",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    resourceId: "deposit-match-review-auth-unassigned",
    rationale: "Firm-wide reviewers can list synthetic deposit-match reviewer decisions.",
  },
  {
    id: "deposit-match-review:assigned:list-visible",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "deposit-match-review-auth-assigned",
    rationale: "Assigned staff can list deposit-match reviewer decisions for their matter.",
  },
  {
    id: "deposit-match-review:unassigned:list-hidden",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "read",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "deposit-match-review-auth-unassigned",
    rationale: "Matter-scoped staff cannot query unassigned deposit-match reviewer decisions.",
  },
  {
    id: "deposit-match-review:portal-client:staff-list-denied",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "deposit-match-review-auth-assigned",
    rationale: "Client-external portal users cannot access staff deposit-match review lists.",
  },
  {
    id: "deposit-match-review:firm-wide:create",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "create",
    relation: "firm_wide_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-admin",
    matterId: "matter-002",
    resourceId: "deposit-match-review-auth-firm-wide-create",
    rationale: "Firm-wide reviewers can create synthetic deposit-match reviewer decisions.",
  },
  {
    id: "deposit-match-review:assigned:create",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "create",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "deposit-match-review-auth-assigned-create",
    rationale: "Assigned staff can create deposit-match reviewer decisions for their matter.",
  },
  {
    id: "deposit-match-review:unassigned:create-denied",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "create",
    relation: "unassigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    matterId: "matter-002",
    resourceId: "deposit-match-review-auth-unassigned-create",
    rationale: "Matter-scoped staff cannot create deposit-match reviewer decisions elsewhere.",
  },
  {
    id: "deposit-match-review:portal-client:create-denied",
    family: "payment_import_deposit_match_review",
    resource: "expense_entry",
    action: "create",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "client-ada",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "deposit-match-review-auth-portal-create",
    rationale: "Client-external portal users cannot create staff deposit-match reviewer decisions.",
  },
  {
    id: "refund-chargeback-review:assigned:list-visible",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "payment-import-review-refund-auth-assigned",
    rationale: "Assigned staff can list refund and chargeback review decisions for their matter.",
  },
  {
    id: "refund-chargeback-review:auditor:list-visible",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "read",
    relation: "auditor_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-refund-chargeback-auditor",
    matterId: "matter-001",
    resourceId: "payment-import-review-refund-auth-assigned",
    rationale: "Auditors can list refund and chargeback review decisions without assignment.",
  },
  {
    id: "refund-chargeback-review:assigned:create",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "create",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "refund-chargeback-review-auth-assigned-create",
    rationale:
      "Assigned staff can record refund and chargeback reviewer decisions for their matter.",
  },
  {
    id: "refund-chargeback-review:auditor:create-denied",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "create",
    relation: "auditor_reviewer",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-refund-chargeback-auditor",
    matterId: "matter-001",
    resourceId: "refund-chargeback-review-auth-auditor-denied",
    rationale: "Auditors can review refund and chargeback decisions but cannot record them.",
  },
  {
    id: "refund-chargeback-review:portal-client:list-denied",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-refund-chargeback-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "payment-import-review-refund-auth-assigned",
    rationale: "Client-external portal users cannot access staff refund and chargeback reviews.",
  },
  {
    id: "refund-chargeback-review:portal-client:create-denied",
    family: "payment_import_refund_chargeback_review",
    resource: "expense_entry",
    action: "create",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-refund-chargeback-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "refund-chargeback-review-auth-portal-denied",
    rationale:
      "Client-external portal users cannot create staff refund and chargeback reviewer decisions.",
  },
  {
    id: "trust-transfer-review:assigned:list-visible",
    family: "trust_transfer_review",
    resource: "trust_ledger",
    action: "read",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "trust-transfer-request-001",
    rationale: "Assigned staff can list trust-transfer review requests for their matter.",
  },
  {
    id: "trust-transfer-review:assigned:approve",
    family: "trust_transfer_review",
    resource: "trust_ledger",
    action: "approve",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "trust-transfer-request-001",
    rationale: "Assigned staff with trust-ledger approval can approve a pending request.",
  },
  {
    id: "trust-transfer-review:auditor:approve-denied",
    family: "trust_transfer_review",
    resource: "trust_ledger",
    action: "approve",
    relation: "auditor_reviewer",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-trust-transfer-auditor",
    matterId: "matter-001",
    resourceId: "trust-transfer-request-001",
    rationale: "Auditors can inspect trust-transfer records but cannot approve or link them.",
  },
  {
    id: "trust-transfer-review:bookkeeper:approve-denied",
    family: "trust_transfer_review",
    resource: "trust_ledger",
    action: "approve",
    relation: "billing_bookkeeper",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-trust-transfer-bookkeeper",
    matterId: "matter-001",
    resourceId: "trust-transfer-request-001",
    rationale:
      "Billing bookkeepers can read/export trust records but cannot approve or link trust-transfer requests.",
  },
  {
    id: "trust-transfer-review:portal-client:staff-list-denied",
    family: "trust_transfer_review",
    resource: "trust_ledger",
    action: "read",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-trust-transfer-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "trust-transfer-request-001",
    rationale: "Client-external portal users cannot access staff trust-transfer review routes.",
  },
  {
    id: "staff-report-export:auditor:workspace-visible",
    family: "staff_report_export",
    resource: "report",
    action: "read",
    relation: "auditor_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-report-auditor",
    resourceId: "staff-report-history-test",
    rationale: "Auditors can read the staff Reports workspace and bounded export history.",
  },
  {
    id: "staff-report-export:bookkeeper:create",
    family: "staff_report_export",
    resource: "report",
    action: "export",
    relation: "billing_bookkeeper",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-report-bookkeeper",
    resourceId: "staff-report-export-auth-bookkeeper",
    rationale: "Billing bookkeepers can request manual staff report exports.",
  },
  {
    id: "staff-report-export:assigned:create-denied",
    family: "staff_report_export",
    resource: "report",
    action: "export",
    relation: "assigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    resourceId: "staff-report-export-auth-assigned-denied",
    rationale: "Matter-assigned staff without firm reporting access cannot request report exports.",
  },
  {
    id: "staff-report-export:portal-client:create-denied",
    family: "staff_report_export",
    resource: "report",
    action: "export",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-report-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "staff-report-export-auth-portal-denied",
    rationale: "Client-external portal users cannot request staff report exports.",
  },
  {
    id: "audit-export:auditor:create",
    family: "audit_export",
    resource: "audit_log",
    action: "export",
    relation: "auditor_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-audit-auditor",
    resourceId: "audit-export-auth-auditor",
    rationale: "Auditors can request redacted audit exports.",
  },
  {
    id: "audit-export:bookkeeper:create-denied",
    family: "audit_export",
    resource: "audit_log",
    action: "export",
    relation: "billing_bookkeeper",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-audit-bookkeeper",
    resourceId: "audit-export-auth-bookkeeper-denied",
    rationale: "Billing bookkeepers can read audit summaries but cannot export the audit log.",
  },
  {
    id: "audit-export:assigned:create-denied",
    family: "audit_export",
    resource: "audit_log",
    action: "export",
    relation: "assigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-staff",
    resourceId: "audit-export-auth-staff-denied",
    rationale: "Assigned staff without audit export permission cannot request audit exports.",
  },
  {
    id: "audit-export:portal-client:create-denied",
    family: "audit_export",
    resource: "audit_log",
    action: "export",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-audit-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "audit-export-auth-portal-denied",
    rationale: "Client-external portal users cannot request audit exports.",
  },
  {
    id: "billing-export:assigned:matter-create",
    family: "billing_export",
    resource: "trust_ledger",
    action: "export",
    relation: "assigned_matter_staff",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-licensee",
    matterId: "matter-001",
    resourceId: "billing-export-auth-assigned",
    rationale: "Assigned staff can request a matter-scoped billing export for their matter.",
  },
  {
    id: "billing-export:auditor:firm-create",
    family: "billing_export",
    resource: "trust_ledger",
    action: "export",
    relation: "auditor_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-billing-export-auditor",
    resourceId: "billing-export-auth-auditor",
    rationale: "Auditors can request firm-scoped billing exports.",
  },
  {
    id: "billing-export:bookkeeper:firm-create",
    family: "billing_export",
    resource: "trust_ledger",
    action: "export",
    relation: "billing_bookkeeper",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-billing-export-bookkeeper",
    resourceId: "billing-export-auth-bookkeeper",
    rationale: "Billing bookkeepers can request firm-scoped billing exports.",
  },
  {
    id: "billing-export:portal-client:create-denied",
    family: "billing_export",
    resource: "trust_ledger",
    action: "export",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-billing-export-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "billing-export-auth-portal-denied",
    rationale: "Client-external portal users cannot request billing exports.",
  },
  {
    id: "jurisdictional-trust-export:auditor:report-visible",
    family: "jurisdictional_trust_export",
    resource: "trust_ledger",
    action: "read",
    relation: "auditor_reviewer",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-jurisdictional-trust-auditor",
    resourceId: "jurisdictional-trust-report-auth-auditor",
    rationale: "Auditors can read firm-wide jurisdictional trust report aggregates.",
  },
  {
    id: "jurisdictional-trust-export:bookkeeper:create",
    family: "jurisdictional_trust_export",
    resource: "trust_ledger",
    action: "export",
    relation: "billing_bookkeeper",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "user-jurisdictional-trust-bookkeeper",
    resourceId: "jurisdictional-trust-export-auth-bookkeeper",
    rationale: "Billing bookkeepers can request jurisdictional trust exports.",
  },
  {
    id: "jurisdictional-trust-export:assigned:create-denied",
    family: "jurisdictional_trust_export",
    resource: "trust_ledger",
    action: "export",
    relation: "assigned_matter_staff",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-licensee",
    resourceId: "jurisdictional-trust-export-auth-assigned-denied",
    rationale:
      "Matter-assigned staff cannot request firm-wide jurisdictional trust exports without firm-wide ledger authority.",
  },
  {
    id: "jurisdictional-trust-export:portal-client:create-denied",
    family: "jurisdictional_trust_export",
    resource: "trust_ledger",
    action: "export",
    relation: "external_portal_contact",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "user-jurisdictional-trust-client-external",
    matterId: "matter-001",
    contactId: "contact-ada",
    resourceId: "jurisdictional-trust-export-auth-portal-denied",
    rationale: "Client-external portal users cannot request jurisdictional trust exports.",
  },
  {
    id: "portal-link:public-share:metadata-visible",
    family: "portal_link",
    resource: "share_link",
    action: "read",
    relation: "public_share_token_holder",
    expectedDecision: "allow",
    listVisible: true,
    subjectId: "public-share-token",
    matterId: "matter-001",
    resourceId: "share-link-active",
    rationale: "Valid share tokens list sanitized share and document metadata only.",
  },
  {
    id: "portal-link:expired-share:hidden",
    family: "portal_link",
    resource: "share_link",
    action: "read",
    relation: "expired_public_share_token_holder",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "expired-share-token",
    matterId: "matter-001",
    resourceId: "share-link-expired",
    rationale: "Expired share tokens return a hidden result and record an expired outcome.",
  },
  {
    id: "portal-link:revoked-share:hidden",
    family: "portal_link",
    resource: "share_link",
    action: "read",
    relation: "revoked_public_share_token_holder",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "revoked-share-token",
    matterId: "matter-001",
    resourceId: "share-link-revoked",
    rationale: "Revoked share tokens return a hidden result and record a revoked outcome.",
  },
  {
    id: "portal-link:email-unverified:denied",
    family: "portal_link",
    resource: "share_link",
    action: "read",
    relation: "unverified_public_share_token_holder",
    expectedDecision: "deny",
    listVisible: false,
    subjectId: "email-verification-share-token",
    matterId: "matter-001",
    resourceId: "share-link-email-verification",
    rationale: "Email-verification share links deny reads until the verification code is accepted.",
  },
];
