export type FinancialExportFieldProfileId =
  | "billing_operational_records_json"
  | "jurisdictional_trust_summary_json";

export interface FinancialExportFieldProfile {
  id: FinancialExportFieldProfileId;
  label: string;
  format: "json";
  source: "generated_local_projection";
  manualDownloadOnly: true;
  scheduledDelivery: false;
  storesRawExportBody: false;
  fieldKeys: readonly string[];
}

const billingOperationalRecordFieldKeys = [
  "fieldProfile",
  "generatedAt",
  "reportType",
  "reportScope",
  "matterId",
  "billingPosture",
  "trustTransferPolicy",
  "timeEntries",
  "timeEntries.id",
  "timeEntries.firmId",
  "timeEntries.matterId",
  "timeEntries.userId",
  "timeEntries.performedAt",
  "timeEntries.minutes",
  "timeEntries.rateCents",
  "timeEntries.rateRuleId",
  "timeEntries.rateSnapshot",
  "timeEntries.narrative",
  "timeEntries.billable",
  "timeEntries.billingStatus",
  "expenseEntries",
  "expenseEntries.id",
  "expenseEntries.firmId",
  "expenseEntries.matterId",
  "expenseEntries.incurredAt",
  "expenseEntries.amountCents",
  "expenseEntries.category",
  "expenseEntries.description",
  "expenseEntries.reimbursable",
  "expenseEntries.billingStatus",
  "invoices",
  "invoices.id",
  "invoices.firmId",
  "invoices.matterId",
  "invoices.clientContactId",
  "invoices.invoiceNumber",
  "invoices.status",
  "invoices.approvedAt",
  "invoices.issuedAt",
  "invoices.dueAt",
  "invoices.memo",
  "invoices.createdByUserId",
  "invoices.createdAt",
  "invoices.voidedAt",
  "invoices.subtotalCents",
  "invoices.taxCents",
  "invoices.totalCents",
  "invoices.paidCents",
  "invoices.balanceDueCents",
  "payments",
  "payments.id",
  "payments.firmId",
  "payments.matterId",
  "payments.invoiceId",
  "payments.clientContactId",
  "payments.receivedAt",
  "payments.amountCents",
  "payments.method",
  "payments.reference",
  "payments.status",
  "payments.receivedByUserId",
  "payments.reconciledAt",
  "payments.reconciledByUserId",
  "paymentRequests",
  "paymentRequests.id",
  "paymentRequests.firmId",
  "paymentRequests.matterId",
  "paymentRequests.invoiceId",
  "paymentRequests.clientContactId",
  "paymentRequests.status",
  "paymentRequests.amountCents",
  "paymentRequests.currency",
  "paymentRequests.hostedPath",
  "paymentRequests.delivery",
  "paymentRequests.reminder",
  "paymentRequests.paymentPlan",
  "paymentRequests.creditWriteOffPosture",
  "paymentRequests.processor",
  "paymentRequests.createdByUserId",
  "paymentRequests.createdAt",
  "paymentRequests.updatedAt",
  "paymentRequests.expiresAt",
  "trustTransferRequests",
  "trustTransferRequests.id",
  "trustTransferRequests.firmId",
  "trustTransferRequests.matterId",
  "trustTransferRequests.clientContactId",
  "trustTransferRequests.invoiceId",
  "trustTransferRequests.requestedByUserId",
  "trustTransferRequests.amountCents",
  "trustTransferRequests.status",
  "trustTransferRequests.reason",
  "trustTransferRequests.requestedAt",
  "trustTransferRequests.reviewedByUserId",
  "trustTransferRequests.reviewedAt",
  "trustTransferRequests.ledgerTransactionId",
] as const;

const jurisdictionalTrustSummaryFieldKeys = [
  "fieldProfile",
  "groupBy",
  "filters",
  "dimensionOptions",
  "dimensionOptions.jurisdictions",
  "dimensionOptions.practiceAreas",
  "dimensionOptions.clinicProgramIds",
  "dimensionOptions.restrictedFundReviewStatuses",
  "summaries",
  "summaries.jurisdiction",
  "summaries.groupBy",
  "summaries.dimensionKey",
  "summaries.dimensionLabel",
  "summaries.dimensions",
  "summaries.practiceArea",
  "summaries.clinicProgramId",
  "summaries.restrictedFundReviewStatus",
  "summaries.matterCount",
  "summaries.trustBalanceCents",
  "summaries.pendingApprovalCount",
  "summaries.rejectedApprovalCount",
  "summaries.exceptionReconciliationCount",
  "summaries.importedStatementRowCount",
  "summaries.matchedStatementRowCount",
  "summaries.unmatchedStatementRowCount",
  "summaries.totalVarianceCents",
  "summaries.unreconciledAccountCount",
  "summaries.overdrawnBalanceCount",
  "summaries.compliancePosture",
  "compliancePosture",
] as const;

export const financialExportFieldProfiles = {
  billingOperationalRecordsJson: {
    id: "billing_operational_records_json",
    label: "Billing operational records JSON",
    format: "json",
    source: "generated_local_projection",
    manualDownloadOnly: true,
    scheduledDelivery: false,
    storesRawExportBody: false,
    fieldKeys: billingOperationalRecordFieldKeys,
  },
  jurisdictionalTrustSummaryJson: {
    id: "jurisdictional_trust_summary_json",
    label: "Jurisdictional trust summary JSON",
    format: "json",
    source: "generated_local_projection",
    manualDownloadOnly: true,
    scheduledDelivery: false,
    storesRawExportBody: false,
    fieldKeys: jurisdictionalTrustSummaryFieldKeys,
  },
} as const satisfies Record<string, FinancialExportFieldProfile>;
