export const operationsStaffPages = {
  tasks: {
    key: "tasks",
    id: "operations.tasks",
    componentName: "OperationsTasksPage",
    routeId: "tasks",
    sectionKey: "tasks",
    area: "operations",
    slug: "tasks",
    title: "Tasks",
    shortLabel: "Tasks",
    canonicalPath: "/operations/tasks",
    currentDashboardHref: "/?section=tasks",
    currentDashboardLabel: "Task deadline workbench",
    scopeLabel: "Firm operations",
    contextLabel: "Visible matters and staff users",
    availability: "firm",
    requiresMatterContext: false,
    primarySurface: "Staff tasks, matter-linked deadlines, follow-up cues, and archived filters",
    sourceModule: "apps/web/app/dashboard/tasks-section.tsx",
    summary:
      "Review staff tasks, matter-linked deadlines, follow-up cues, and archived-task filters.",
    guardrails: [
      "Keep task mutations on existing authenticated staff APIs.",
      "Do not auto-create follow-up tasks from review cues.",
      "Preserve matter-scoped visibility for task context.",
    ],
  },
  shareLinks: {
    key: "share-links",
    id: "operations.share-links",
    componentName: "OperationsShareLinksPage",
    routeId: "shares",
    sectionKey: "shares",
    area: "operations",
    slug: "share-links",
    title: "Share Links",
    shortLabel: "Shares",
    canonicalPath: "/operations/share-links",
    currentDashboardHref: "/?section=shares",
    currentDashboardLabel: "Share links workspace",
    scopeLabel: "Matter operations",
    contextLabel: "Selected matter and eligible client contacts",
    availability: "mixed",
    requiresMatterContext: true,
    primarySurface: "Matter-scoped client share links and client account setup tokens",
    sourceModule: "apps/web/app/dashboard/share-links-section.tsx",
    resourceModule: "apps/web/app/_features/share-links/server-resources.ts",
    summary: "Create and review matter-scoped client share links and client account setup tokens.",
    guardrails: [
      "Do not change public share-link runner routes or token handling.",
      "Keep share creation matter-scoped and authorization-backed.",
      "Only surface one-time secrets through the existing staff reveal flow.",
    ],
  },
  externalUploads: {
    key: "external-uploads",
    id: "operations.external-uploads",
    componentName: "OperationsExternalUploadsPage",
    routeId: "externalUploads",
    sectionKey: "externalUploads",
    area: "operations",
    slug: "external-uploads",
    title: "External Uploads",
    shortLabel: "Uploads",
    canonicalPath: "/operations/external-uploads",
    currentDashboardHref: "/?section=externalUploads",
    currentDashboardLabel: "External uploads workspace",
    scopeLabel: "Matter operations",
    contextLabel: "Selected matter and uploaded documents",
    availability: "mixed",
    requiresMatterContext: true,
    primarySurface:
      "Upload links, uploaded-document review, checksum, scan, duplicate, and access-proof cues",
    sourceModule: "apps/web/app/dashboard/external-uploads-section.tsx",
    resourceModule: "apps/web/app/_features/external-uploads/server-resources.ts",
    summary:
      "Create upload links, review uploaded documents, and keep checksum, scan, duplicate, and access-proof cues visible.",
    guardrails: [
      "Do not change public external-upload runner routes or upload contracts.",
      "Preserve existing document review decisions and scan/checksum posture.",
      "Keep storage and provider behavior on existing routes.",
    ],
  },
  signatures: {
    key: "signatures",
    id: "operations.signatures",
    componentName: "OperationsSignaturesPage",
    routeId: "signatures",
    sectionKey: "signatures",
    area: "operations",
    slug: "signatures",
    title: "Signatures",
    shortLabel: "Signatures",
    canonicalPath: "/operations/signatures",
    currentDashboardHref: "/?section=signatures",
    currentDashboardLabel: "Signature requests",
    scopeLabel: "Matter operations",
    contextLabel: "Selected matter signature requests",
    availability: "mixed",
    requiresMatterContext: true,
    primarySurface:
      "Signature requests, envelope validation posture, signer roles, and field-placement counts",
    sourceModule: "apps/web/app/dashboard/signatures-section.tsx",
    summary:
      "Review matter signature requests, envelope validation posture, signer roles, and field-placement counts.",
    guardrails: [
      "Keep embedded signature provider contracts unchanged.",
      "Do not add provider-specific signature workflow assumptions.",
      "Preserve matter-scoped signature visibility.",
    ],
  },
  intake: {
    key: "intake",
    id: "operations.intake",
    componentName: "OperationsIntakePage",
    routeId: "intake",
    sectionKey: "intake",
    area: "operations",
    slug: "intake",
    title: "Intake",
    shortLabel: "Intake",
    canonicalPath: "/operations/intake",
    currentDashboardHref: "/?section=intake",
    currentDashboardLabel: "Intake workspace",
    scopeLabel: "Mixed operations",
    contextLabel: "Selected matter, templates, and intake leads",
    availability: "mixed",
    requiresMatterContext: true,
    primarySurface:
      "Intake links, submitted intake decisions, template QA, public consultation intake, and legal-clinic cues",
    sourceModule: "apps/web/app/dashboard/intake-section.tsx",
    resourceModule: "apps/web/app/_features/intake/server-resources.ts",
    summary:
      "Review intake links, submitted intake decisions, template QA, public consultation intake, and legal-clinic cues.",
    guardrails: [
      "Do not change public intake runner routes or submitted-answer contracts.",
      "Keep QA scenarios staff-only and synthetic.",
      "Do not auto-create matters from intake review cues.",
    ],
  },
  queues: {
    key: "queues",
    id: "operations.queues",
    componentName: "OperationsQueuesPage",
    routeId: "queues",
    sectionKey: "queues",
    area: "operations",
    slug: "queues",
    title: "Operational Queues",
    shortLabel: "Queues",
    canonicalPath: "/operations/queues",
    currentDashboardHref: "/?section=queues",
    currentDashboardLabel: "Operational queues",
    scopeLabel: "Firm operations",
    contextLabel: "Queue, provider, connector, and worker health",
    availability: "firm",
    requiresMatterContext: false,
    primarySurface:
      "Queue health, provider posture, worker runs, connector recovery, saved views, and AI operational proposals",
    sourceModule: "apps/web/app/dashboard/queues-section.tsx",
    resourceModule: "apps/web/app/_features/operations/server-resources.ts",
    summary:
      "Review queue health, provider posture, worker runs, connector recovery, saved views, and AI operational proposals.",
    guardrails: [
      "Preserve existing queue, worker-run, and connector recovery contracts.",
      "Keep provider recovery staff-confirmed.",
      "Do not widen queue permissions from the UI.",
    ],
  },
} as const;

export type OperationsStaffPageKey = keyof typeof operationsStaffPages;
export type OperationsStaffPageDefinition = (typeof operationsStaffPages)[OperationsStaffPageKey];
